FROM ubuntu:24.04
MAINTAINER Andrew Crabb <crabba@amazon.com>

LABEL \
    description="Image for Fulcrum Genomics fgbio"

RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y \
#    build-essential \
#    default-jdk \
    default-jre \
    software-properties-common \
    unzip \
    wget && \
    rm -rf /var/lib/apt/lists/*
    
# ENV fgbio_user fgbio
# RUN useradd -ms /bin/bash ${fgbio_user}
# USER ${fgbio_user}

ENV fgbio_version 2.3.0
RUN wget --directory-prefix=/root https://github.com/fulcrumgenomics/fgbio/releases/download/${fgbio_version}/fgbio-${fgbio_version}.jar
